### PR TITLE
Update French translation (for 0.9.5 release)

### PR DESCRIPTION
**Pull request by david-geiger**
- by David GEIGER david.david@mageialinux-online.org
- by Adrien DAUGABEL adrien.d@mageialinux-online.org

### CODE REVIEW

**Comment by Faster3ck** [comment]
Thank you very much for updating the french localization. :)

**Comment by david-geiger** [comment]
You're welcome :)

Is it possible to add Adrien DAUGABEL adrien.d@mageialinux-online.org and David GEIGER david.david@mageialinux-online.org as French Translatrors in about dialog?

**Comment by Faster3ck** [comment]
Yes, of course. I will add your credits in about dialog the sooner possibile. :)

**Comment by Faster3ck** [comment]
Credits added! :)

**Pull request merged**
